# Generated by Django 4.0 on 2024-02-06 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='items',
        ),
        migrations.AddField(
            model_name='cart',
            name='items',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
