# Generated by Django 4.0 on 2024-02-06 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce_app', '0003_cart_remove_category_descriptions_cartitem_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='items',
            field=models.ManyToManyField(through='ecommerce_app.CartItem', to='ecommerce_app.Product'),
        ),
    ]
