# Generated by Django 4.0 on 2024-02-06 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce_app', '0004_alter_cart_items'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(default='img.png', upload_to=''),
        ),
    ]
